name: flutter_kalkulator
description: A simple calculator built with Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  math_expressions: ^2.0.0
  google_fonts: ^6.2.1
  animate_do: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - logo.png

